"""add_user_streak_tracking

Revision ID: 9996f9fe8f76
Revises: 7a23ac4a6376
Create Date: 2026-01-19 18:13:41.525417

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9996f9fe8f76'
down_revision: Union[str, None] = '7a23ac4a6376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires a default value when adding NOT NULL columns to existing tables
    op.add_column('users', sa.Column('daily_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_study_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_study_date')
    op.drop_column('users', 'daily_streak')
    # ### end Alembic commands ###

